services:
    cli:
        build:
            args:
                USER_NAME: ${USER_NAME}
                REPO: ${REPO}
            context: ..
            dockerfile: .docker/Dockerfile
        environment:
          AWS_PROFILE: sap_dev
          AWS_DEFAULT_REGION: us-east-1
          SAM_CLI_TELEMETRY: 0
        image: aws-cloudformations
        privileged: true
        volumes:
            - ~/.aws/:/home/${USER_NAME}/.aws/
            - ../:/home/${USER_NAME}/src/${REPO}
        working_dir: /home/${USER_NAME}/src/${REPO}
